webdav: fix crash while scanning an empty archive
While scanning an emptry archive webdav-listdir returns Null instead of
an emptry list causing the following exception:

 Bob version 1.1.1.dev28+g8bb51c4c
 Traceback (most recent call last):
   File "bob/pym/bob/scripts.py", line 157, in catchErrors
     ret = fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
   File "bob/pym/bob/scripts.py", line 267, in cmd
     ret = cmd(args.args, bobRoot)
           ^^^^^^^^^^^^^^^^^^^^^^^
   File "bob/pym/bob/scripts.py", line 18, in __archive
     doArchive(*args, **kwargs)
   File "bob/pym/bob/cmds/archive.py", line 556, in doArchive
     availableArchiveCmds[args.subcommand][0](archivers, args.args)
   File "bob/pym/bob/cmds/archive.py", line 476, in doArchiveFind
     if not scanner.scan(args.verbose) and args.fail:
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "bob/pym/bob/cmds/archive.py", line 99, in scan
     for l1 in self.__archiver.listDir("."):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "bob/pym/bob/archive.py", line 651, in listDir
     return self._listDir(path)
            ^^^^^^^^^^^^^^^^^^^
   File "bob/pym/bob/archive.py", line 979, in _listDir
     for info in path_info:
 TypeError: 'NoneType' object is not iterable